conveyordata/data-product-portal

README.md

Small pull request to readme to make it more understandable and lighter to read.

Add readme updates

---

compose.yaml

Updated the healtcheck to go quicker

Migrated to use standard postgres alpine image

---

backend/app/data_product_memberships/service.py
backend/app/data_product_types/enums.py
backend/app/data_products/service.py
backend/tests/conftest.py
backend/tests/data_product_memberships/test_router.py
backend/tests/data_product_types/test_router.py
backend/tests/data_products/test_router.py
backend/tests/data_products_datasets/test_router.py
backend/tests/datasets/test_router.py

Written tests for the following routers:
- data_products
- datasets
- data_products_datasets
- data_products_memberships
- data_product_types

Test expansion

---

frontend/package-lock.json
frontend/package.json

Reverts conveyordata/data-product-portal#431

Revert "Bump i18next-http-backend from 2.6.2 to 2.7.0 in /frontend"

---

frontend/src/components/layout/auth/auth.layout.tsx

Add deep linking to authentication

---

backend/app/users/router.py
backend/app/users/schema.py
backend/app/users/service.py

Endpoint to create new users

---

backend/app/data_products/schema_base_get.py

This caused issues with getting and creating new DPs

Reset about field to optional again

---

frontend/public/locales/en/translation.json
frontend/src/components/layout/navbar/breadcrumbs/breadcrumbs.component.tsx
frontend/src/components/layout/sidebar/sidebar.component.tsx

Datasets tab renamed to Marketplace in menu

---

frontend/package-lock.json
frontend/package.json

Reverts conveyordata/data-product-portal#791

Revert "Bump typescript from 5.7.3 to 5.8.2 in /frontend"

---

frontend/package-lock.json
frontend/package.json
frontend/src/main.tsx

Also install the antd-react19 compatibility plugin.
Fixes https://github.com/conveyordata/data-product-portal/security/dependabot/31

Increment babel dependencies

---

README.md
backend/app/database/alembic/versions/2025_03_31_1609-48c52a42d7a2_add_global_role_assignments.py
backend/app/db_tool.py
backend/app/role_assignments/data_product/router.py
backend/app/role_assignments/data_product/tasks.py
backend/app/role_assignments/dataset/tasks.py
backend/app/role_assignments/global_/model.py
backend/app/role_assignments/global_/router.py
backend/app/role_assignments/global_/schema.py
backend/app/role_assignments/global_/service.py
backend/app/role_assignments/global_/tasks.py
backend/app/role_assignments/router.py
backend/app/role_assignments/tasks.py
backend/app/roles/model.py
backend/app/roles/schema.py
backend/app/roles/service.py
backend/sample_data.sql
backend/tests/app/role_assignments/global_/test_router.py
backend/tests/app/roles/test_router.py
backend/tests/factories/__init__.py
backend/tests/factories/role_assignment_global.py
frontend/src/pages/roles/components/roles-table.component.tsx
frontend/src/types/roles/role.contract.ts

- Add service and table for global role assignments
- Modify the casbin policy to support global roles
- Make the admin role a special case of a global role
- Update the role configuration page in the frontend to keep everything ordered
Closes #870

Add assignments for global roles

---

frontend/src/components/layout/auth/auth.layout.tsx

OICD: background token refresh does not trigger UI loading state

---

frontend/public/locales/en/translation.json
frontend/src/pages/home/components/pending-requests-inbox/pending-requests-inbox.module.scss
frontend/src/pages/home/components/pending-requests-inbox/pending-requests-inbox.tsx
frontend/src/pages/home/home.page.tsx

cleaner display when no requests are pending

---

backend/app/core/auth/device_flows/schema.py
backend/app/core/aws/refreshable_session.py
backend/app/core/config/env_var_parser.py
backend/app/data_outputs_datasets/schema.py
backend/app/data_product_memberships/schema.py
backend/app/data_product_memberships/schema_get.py
backend/app/data_products_datasets/schema.py

Refactor replacing occurences of "| None" with Optional as it is preffered.

Refactor replacing occurences of "| None" with Optional

---

backend/app/data_products/service.py

Removed code I stumbled upon that is unreachable.

removed unreachable code & unused function

---

backend/app/migrations/rbac.py

Potential bug in rbac migration on main branch

---

backend/app/authorization/service.py
backend/app/core/authz/authorization.py
backend/pyproject.toml
backend/tests/app/authorization/test_service.py

Fixes the deadlocking issue we've encountered

Update how we clear the casbin table

---

backend/app/database/alembic/versions/2025_03_25_1542-c02e4638423f_add_role_assignments.py
frontend/src/pages/data-output/components/data-output-tabs/dataset-tab/components/dataset-table/dataset-table.component.tsx
frontend/src/pages/data-output/components/data-output-tabs/dataset-tab/components/dataset-table/dataset-table.module.scss

Added pagination to datasets overwiew on data output page

Added pagination to data output page

---

frontend/src/pages/data-output/components/data-output-tabs/dataset-tab/components/dataset-table/dataset-table.module.scss
frontend/src/pages/data-output/components/data-output-tabs/dataset-tab/dataset-tab.module.scss
frontend/src/pages/data-output/components/data-output-tabs/dataset-tab/dataset-tab.tsx
frontend/src/pages/data-product/components/data-product-tabs/data-output-tab/components/data-output-table/data-output-table.module.scss
frontend/src/pages/data-product/components/data-product-tabs/data-output-tab/data-output-tab.module.scss
frontend/src/pages/data-product/components/data-product-tabs/data-output-tab/data-output-tab.tsx
frontend/src/pages/data-product/components/data-product-tabs/dataset-tab/components/dataset-table/dataset-table.module.scss
frontend/src/pages/data-product/components/data-product-tabs/dataset-tab/dataset-tab.module.scss
frontend/src/pages/data-product/components/data-product-tabs/dataset-tab/dataset-tab.tsx
frontend/src/pages/data-product/components/data-product-tabs/team-tab/components/team-table/team-table.module.scss
frontend/src/pages/data-product/components/data-product-tabs/team-tab/team-tab.module.scss
frontend/src/pages/data-product/components/data-product-tabs/team-tab/team-tab.tsx
frontend/src/pages/dataset/components/dataset-tabs/data-output-tab/components/data-output-table/data-output-table.module.scss
frontend/src/pages/dataset/components/dataset-tabs/data-output-tab/data-output-tab.module.scss
frontend/src/pages/dataset/components/dataset-tabs/data-output-tab/data-output-tab.tsx
frontend/src/pages/dataset/components/dataset-tabs/data-product-tab/components/data-product-table/data-product-table.module.scss
frontend/src/pages/dataset/components/dataset-tabs/data-product-tab/data-product-tab.module.scss
frontend/src/pages/dataset/components/dataset-tabs/data-product-tab/data-product-tab.tsx
frontend/src/pages/dataset/components/dataset-tabs/team-tab/components/team-table/team-table.module.scss
frontend/src/pages/dataset/components/dataset-tabs/team-tab/team-tab.module.scss
frontend/src/pages/dataset/components/dataset-tabs/team-tab/team-tab.tsx

Whitespacing adjusted to flow better with pagination

---

frontend/src/pages/data-product/components/data-product-actions/data-product-actions.component.tsx

Small UI change for the data product page

Only show tiles of platforms that are currently configured in frontend.

---

backend/app/data_outputs/service.py
backend/tests/app/data_outputs/test_router.py

- Resolved issue with conditional branch for product aligned outputs accessing field that is no longer available
- Created additional test case to test product aligned output

Fix issue when creating product aligned data output

---

backend/app/data_products/router.py
backend/app/datasets/router.py
backend/app/role_assignments/data_product/schema.py
backend/app/role_assignments/data_product/service.py
backend/app/role_assignments/dataset/schema.py
backend/app/role_assignments/dataset/service.py
backend/app/role_assignments/global_/service.py
backend/tests/app/datasets/test_router.py
backend/tests/app/role_assignments/data_product/test_router.py
backend/tests/app/role_assignments/dataset/test_router.py
frontend/src/components/data-access/user-access-overview/user-access-overview.component.tsx
frontend/src/components/data-products/data-product-form/data-product-form.component.tsx
frontend/src/components/datasets/dataset-form/dataset-form.component.tsx
frontend/src/pages/data-product/components/data-product-tabs/team-tab/components/team-table/team-table-columns.tsx
frontend/src/pages/dataset/components/dataset-tabs/team-tab/components/team-table/team-table-columns.tsx
frontend/src/store/features/api/tag-types.ts
frontend/src/store/features/role-assignments/data-product-roles-api-slice.ts
frontend/src/store/features/role-assignments/dataset-roles-api-slice.ts
frontend/src/utils/table-sorter.helper.ts

- Improve usage of tags for assignments
- Prevent changing the last owner through the UI
- Improve sorting stability
- Fix bug when creating a product as an admin

More RBAC fixes

---

frontend/src/pages/data-output/components/data-output-description/data-output-description.tsx
frontend/src/pages/data-output/data-output.page.tsx
frontend/src/pages/data-product/components/data-product-description/data-product-description.tsx
frontend/src/pages/data-product/data-product.page.tsx
frontend/src/pages/dataset/components/dataset-description/dataset-description.tsx
frontend/src/pages/dataset/dataset.page.tsx

Crucial missing information in the UI

Add namespace to the 3 detailed pages

---

backend/app/authorization/service.py
backend/app/core/auth/device_flows/service.py
backend/app/core/auth/jwt.py
backend/app/core/authz/authorization.py
backend/app/core/aws/boto3_clients.py
backend/app/core/aws/refresh_infrastructure_lambda.py
backend/app/core/email/send_mail.py
backend/app/core/errors/error_handling.py
backend/app/core/logging/__init__.py
backend/app/core/logging/scarf_analytics.py
backend/app/core/webhooks/webhook.py
backend/app/graph/service.py
backend/app/main.py
backend/app/role_assignments/auth.py
backend/app/role_assignments/global_/auth.py
backend/app/roles/auth.py
backend/app/settings.py

Shorten `logger` import
Remove redundant logging from Scarf

Fix casbin resync, also cleanup logging

---

backend/app/platform_service_configurations/schema.py
docs/package-lock.json
frontend/package-lock.json
frontend/package.json
frontend/src/api/api-urls.ts
frontend/src/components/data-access/user-access-overview/user-access-overview.component.tsx
frontend/src/components/data-products/data-product-form/data-product-form.component.tsx
frontend/src/components/datasets/dataset-form/dataset-form.component.tsx
frontend/src/components/environment-config-create/components/environment-config-create-form.component.tsx
frontend/src/components/layout/navbar/breadcrumbs/breadcrumbs.component.tsx
frontend/src/pages/home/components/data-products-inbox/data-products-inbox.tsx
frontend/src/pages/home/components/datasets-inbox/datasets-inbox.tsx
frontend/src/pages/home/components/pending-requests-inbox/pending-requests-inbox.module.scss
frontend/src/pages/settings/components/settings-tabs/components/data-product-settings-table/data-product-settings-table.component.tsx
frontend/src/pages/users/components/users-table/users-table.component.tsx
frontend/src/store/features/roles/roles-api-slice.ts
frontend/src/types/users/index.ts
frontend/src/vite-env.d.ts

Biggest functional change is changing the breadcrumb for the home page from `<HOME> / <HOME> 'Home'` to `<HOME> 'Home'`

Set of small fixes for the frontend
