conveyordata/data-product-portal

- compose.yaml
We now have a health check in the postgres db
and wait until the service is healthy in the backend. Before the backend would crash because postgres was not yet properly started
> Wait until postgres ready in backend

- compose.yaml
- nginx/nginx.conf
…ver Block
- Added `proxy_set_header` directives to the /api and / locations in the main server block to forward headers:
- `Host` to preserve the original host header.
- `X-Real-IP` to pass the client’s real IP address.
- `X-Forwarded-For` to pass the original client’s IP address through proxy servers.
- `X-Forwarded-Proto` to pass the original protocol (HTTP or HTTPS).
- Introduced a new server block listening on port 5050 for direct backend access:
- Configured to forward necessary headers similar to the main server block.
These changes improve the transparency and request forward to  access swagger API on port 5050.
> Nginx Configuration with Additional Proxy Headers for Swagger 

- compose.yaml
Add defaults for environment variables.
Docker compose picks these up automatically from `.env` file. With the moving of the `.env` file to the backend and with that file being optional, docker compose might have behaved weirdly.
This could have resulted in not being able to connect to the postgresdb or not having the right frontend config (missing `$PWD`
> Add defaults for missing env vars

- integrations/terraform/modules/data_products/data_access/locals.tf
An invalid index was used in the terraform code due to a rename of data_ids to data_outputs.
> Fix invalid index in data-access terraform code

- backend/app/core/auth/router.py
- backend/app/data_products/router.py
- backend/app/data_products/service.py
- backend/app/dependencies.py
- backend/tests/data_products/test_router.py
- backend/tests/data_products_datasets/test_router.py
Some endpoints were completely unprotected. They did not check whether or not you were a member / owner for a product.
E.g. the request credentials from AWS endpoint.
This is a big security risk.
Now all endpoints from the data products route are at least secured. The rest can be refactored once this method is approved and tested
> Improve endpoint security with data product role dependency

- backend/Dockerfile
Reverts conveyordata/data-product-portal#230
> Revert "Bump python from 3.12-slim-bookworm to 3.13-slim-bookworm in /backend"

- .github/workflows/cli-workflow.yml
- .github/workflows/tests.yml
- cli/.gitignore
- cli/.goreleaser.yaml
- Move .goreleaser inside the cli/ directory
- Use the go version of the go.mod file
- Include /vendor directory in .gitignore
- Enable caching
> Update CLI workflow

- .github/workflows/cli-workflow.yml
- .github/workflows/docker-build-main.yml
- .github/workflows/nightly-build.yml
- .github/workflows/platform-workflow.yml
- .github/workflows/scorecard.yml
- .github/workflows/tests.yml
Relevant info: https://www.stepsecurity.io/blog/pinning-github-actions-for-enhanced-security-a-complete-guide
It is less readable unfortunately (hence the comments), but all code quality / security checks recommend us to do this.
It will also reduce the clutter in the alerts from said tools
> Pin all actions to hash as recommended by codeQL and security analysis

- backend/test-compose.yaml
- compose.yaml
Aligned both to the latest 16.x releases of the bitnami (VMware) images.
These are smaller and supposedly more secure than the official ones.
> Align postgresql container images

- backend/app/data_outputs/model.py
- backend/app/data_products/model.py
- backend/app/datasets/model.py
- backend/app/tags/model.py
Introduced `back_populates` on `relationship`s between tags and data products, datasets and data outputs to resolve the issue.
> Resolved Tag related SQLAlchemy warnings

- backend/app/data_product_memberships/service.py
- backend/app/data_products/schema.py
- backend/app/data_products/service.py
- backend/app/datasets/schema.py
- backend/app/datasets/schema_get.py
- backend/app/datasets/service.py
- backend/tests/app/data_product_memberships/test_router.py
- backend/tests/app/data_products/test_router.py
- backend/tests/app/datasets/test_router.py
- Added extra validation to DataProductCreate and DataProductUpdate schemas
- Added extra validation to Dataset schema
- Added extra validation on remove_user_from_dataset endpoint
- Added extra validation on data product membership manipulation
> Fix: data product or dataset without owners

- .pre-commit-config.yaml
- backend/app/authorization/router.py
- backend/app/authorization/schema.py
- backend/app/core/authz/authorization.py
- backend/app/settings.py
- backend/app/shared/router.py
- backend/poetry.lock
- backend/pyproject.toml
- backend/tests/app/authorization/test_router.py
- backend/tests/app/core/authz/test_authorization.py
- backend/tests/app/data_outputs/test_router.py
- backend/tests/conftest.py
- frontend/src/api/api-urls.ts
- frontend/src/store/features/authorization/authorization-api-slice.ts
- frontend/src/types/authorization/authorization.contract.ts
- frontend/src/types/authorization/index.ts
Adds an endpoint for the frontend to query resource access.
Can be used to conditionally render UI elements.
Also adds a cache to the backend implementation to avoid this functionality over-querying the casbin table.
> Add endpoint to check resource access

- backend/app/core/authz/authorization.py
- backend/app/settings.py
- backend/tests/conftest.py
Enables to start wiring in the new role enforcement across the API without breaking anything.
Closes #869
> Add feature flag for RBAC to backend settings

- backend/app/core/authz/authorization.py
- backend/app/core/authz/rbac_model.conf
- backend/tests/app/core/authz/test_authorization.py
Forgot about this case when redesigning the casbin policy. Should be good now
> Extend RBAC model to support other global roles than the admin

- backend/Dockerfile
Reverts conveyordata/data-product-portal#978
> Revert "Bump python from 3.12.9-slim-bookworm to 3.13.3-slim-bookworm in /backend"

- backend/app/data_outputs/service.py
- backend/app/data_product_settings/service.py
- backend/app/data_products/service.py
- backend/app/datasets/service.py
- backend/tests/app/data_outputs/test_router.py
- backend/tests/app/data_product_settings/test_router.py
- backend/tests/app/data_products/test_router.py
- backend/tests/app/datasets/test_router.py
- backend/tests/factories/data_product.py
- backend/tests/factories/data_product_setting.py
- backend/tests/factories/dataset.py
- backend/tests/factories/platform.py
- backend/tests/factories/platform_service.py
- frontend/src/components/data-products/data-output-form/data-output-form.component.tsx
- frontend/src/components/data-products/data-product-form/data-product-form.component.tsx
- frontend/src/components/datasets/components/dataset-form.component.tsx
- frontend/src/components/namespace/namespace-form-item.tsx
- frontend/src/pages/settings/components/settings-tabs/components/data-product-settings-table/new-data-product-setting-modal.component.tsx
Fixes the following issues:
- Editing blocked of everything that has a namespace due to namespace validation being triggered and returning duplicate namespace error
- Missing backend validation of namespaces on creation of data product settings and data outputs
> Fix namespace issues

- backend/app/core/auth/auth.py
- backend/app/core/auth/device_flows/service.py
- backend/app/core/auth/service.py
- backend/app/data_outputs/model.py
- backend/app/data_outputs/service.py
- backend/app/data_outputs_datasets/service.py
- backend/app/data_products/model.py
- backend/app/data_products/service.py
- backend/app/data_products_datasets/model.py
- backend/app/data_products_datasets/service.py
- backend/app/datasets/model.py
- backend/app/datasets/service.py
- backend/app/dependencies.py
- backend/app/users/model.py
- backend/app/users/service.py
- backend/tests/app/datasets/test_model.py
Changes:
- Finished assigning default loading strategies to the different models with a focus on avoiding lazy loading
- Added the necessary loading options to all queries (removed some if unnecessary)
- Converted legacy `session.query` API while going over each query
Reasoning behind loading strategies:
- Eagerly load as much as possible using the joined load strategy
- Deliberately cut eager loading as a default in between data products, datasets and data outputs to avoid long (recursive) query chains. By using the default `raise` loading strategy, SQL Alchemy will throw an error when these links between objects are accessed without assigning a loading strategy at query time. This avoids accidental lazy loading.
- The relationships from metadata (e.g. tags, domain, ...) to data …
> SQL Alchemy loading strategy improvements

- backend/app/db_tool.py
Introduced when switching authorization from sync to async #1132
Seeding still happened, but it threw an error message just before the end
```sh
Something went wrong when seeding a coroutine was expected, got None
```
> Fixed an error when seeding the database

- backend/app/data_outputs/service.py
- backend/app/data_products/model.py
- backend/app/data_products/service.py
- backend/app/datasets/service.py
- backend/app/graph/service.py
Fetching all datasets was slowed down due to latest changes with adding `assignments` to the `DataProduct` model with a default `joined` strategy.
Resolved the issue and also added some extra tweaks, which try to avoid similar issues in the future and are generally beneficial for performance of the get all calls:
- Set the default loading strategy of assignments on data products to raise
- Put wildcard raiseload at the end of each loading option to stop further eager loading
- Directly query the database for the graph endpoint to ensure correct loading strategy
> Prevent unnecessary eager loading on get all calls

- frontend/src/theme/antd-theme.ts
- package-lock.json
New theme uses default spacing values instead of previously used ones for the green theme, resulting in some very slight visual changes (some things are slightly out of line). This PR ensures the spacing is unaffected by theme.
This PR does not fix the css bug me & lieven encountered when using the docker container frontend. I am getting very inconsistent results with fixing the margins for this bug (different css results when building the same container multiple times?)
> Spacing fix in theme

- frontend/src/components/history/history-table-event-name.tsx
- frontend/src/utils/history.helper.tsx
Events only show information about other subjects or targets.
Events that don't have this information (e.g. update of tags on a data product) are currently bugged.
When this event happens on a subject, the entire history page crashes because of a single unrenderable event.
> Events referencing only the object itself are not rendered correctly and crash the entire history page

- backend/app/data_products/router.py
- backend/app/datasets/router.py
New data products or datasets create the role assignments but they are not propagated to casbin correctly.
> When new data product / dataset is created, propagate the new owner roles to casbin

- frontend/src/config/posthog-config.ts
- helm/templates/configmap_backend.yaml
- helm/templates/configmap_frontend.yaml
Posthog analytics were always enabled (because of the stringified boolean in Helm)
If disabled Posthog used to still be booted and send some initial events.
> Correct disabling of posthog analytics
